### ISSUE TITLE
Suggestion - Change side of top bar buttons to right and left

### ISSUE THREAD

**Issue by PrincessAkira** [maenDisease/BetterDiscordStuff#17]
Yea i hard dig this theme, but the buttons on the left side are a hardcore dealbreaker for me

**Comment by maenDisease** [comment]
you can disable the macos titlebar by deleting the macostitlebar line inside the theme file

**Comment by PrincessAkira** [comment]
> you can disable the macos titlebar by deleting the macostitlebar line inside the theme file

Well but i want the MacOS buttons.
Just wanna choose what side :D

**Comment by maenDisease** [comment]
I can provide css for this some time soon

**Comment by maenDisease** [comment]
```css
.platform-win .typeWindows-2-g3UY {
    top: -3px;
    left: unset;
    right: 0;
}
```
