### ISSUE TITLE
[Float] Chat Disappears Behind Channels

### ISSUE THREAD

**Issue by sabxtrax** [maenDisease/BetterDiscordStuff#46]
I don't even know how to describe this issue lmao but I disabled any extensions that might've broken and it still gave me this issue.

https://github.com/user-attachments/assets/e291fa24-033a-4160-822e-2b451080f6ce

**Comment by txkyel** [comment]
I found the following rule which seems to interfere with the theme. Disabling it with devtools seems to fix the problem.

```css
html:not(.visual-refresh) .sidebar_a4d4d9:not(.hidden_a4d4d9) {
    width: 240px !important;
}
```

~~I'm assuming that adding  `!important` to [this rule](https://github.com/maenDisease/Float/blob/5edd241b3c918a108fd0b3ccf5d1079fd5a1bef4/src/theme/sidebar/_container.scss#L34) might solve the issue.~~ nvm it looks like the offending rule has priority

**Comment by VANANA-R0TAT3** [comment]
> I found the following rule which seems to interfere with the theme. Disabling it with devtools seems to fix the problem.
> 
> ```css
> html:not(.visual-refresh) .sidebar_a4d4d9:not(.hidden_a4d4d9) {
>     width: 240px !important;
> }
> ```
> 
> ~I'm assuming that adding `!important` to [this rule](https://github.com/maenDisease/Float/blob/5edd241b3c918a108fd0b3ccf5d1079fd5a1bef4/src/theme/sidebar/_container.scss#L34) might solve the issue.~ nvm it looks like the offending rule has priority

heres the fix for anyone struggling to figure out how to disable this,
press ctrl+shift+i and it should open the console up
click the little arrows until you get to the `"<div data-collapsed="false" class="sidebar_a4d4d9">"` bar, type in "html" in the filters bar to find the code thats in the above reply, then just unclick the checkmark at "width"

https://github.com/user-attachments/assets/814593b2-4ca5-4670-82b7-eee93fb77754

**Comment by MaddoxCH** [comment]
Hello guys, you can simply add these lines in your custom css settings in betterdiscord:

```css
html:not(.visual-refresh) div .sidebar_a4d4d9:not(.hidden_a4d4d9) {
    width: unset !important;
}
```

Works like a charm for me :)

**Comment by VANANA-R0TAT3** [comment]
> Hello guys, you can simply add these lines in your custom css settings in betterdiscord:
> 
> ```css
> html:not(.visual-refresh) div .sidebar_a4d4d9:not(.hidden_a4d4d9) {
>     width: unset !important;
> }
> ```
> 
> Works like a charm for me :)

omg this is so much easier, tysm 😭

**Comment by FernLeafie** [comment]
Hello peeps, really happy that this solution exists, but it isn't flawless, somehow it doesn't play nicely on vencord with the ~~spotify controls plugin~~ (i discovered that this also happens with channel names of excessive length), seems to just make the sidebar the width of the longest text in it.
![image](https://github.com/user-attachments/assets/0c24ab65-b3c7-43e1-96e8-17f5903564de)
not especially tech savvy in this department myself, so i cant provide a fix for it, but i wanted to highlight it
thanku all :3

**Comment by F4Xa** [comment]
Hi, just wanted to point out that if you use the solution provided by MaddoxCH the channels with a lot of characters will display like presented in the image.
![image](https://github.com/user-attachments/assets/a2744bd0-e2b3-4851-9c0a-9043a11c3aec)

**Comment by MaddoxCH** [comment]
Hi again guys, to resolve the width problem, you can simply add a max-width to your css, by default it's 240px.

```css
html:not(.visual-refresh) div .sidebar_a4d4d9:not(.hidden_a4d4d9) {
    width: fit-content !important;
    max-width: 240px !important
}
```

**Comment by FakeMichau** [comment]
i did this instead as i still had issue with short channel names causing the bar to shrink
```css
@media (max-width:940px) {
    html:not(.visual-refresh) div .sidebar_a4d4d9:not(.hidden_a4d4d9) {
        width: fit-content !important;
    }
}
```
